Repository jemmia-diamond/frappe, pull requests merged in 2025-05, with the labels that each got.

#3 Settings for lead and customer information
  frappe/automation/workspace/tools/tools.json
  frappe/client.py
  frappe/contacts/doctype/address/address.js
  frappe/contacts/doctype/address/address.json
  frappe/contacts/doctype/address/address.py
  frappe/contacts/doctype/contact/contact.json
  frappe/contacts/doctype/contact/contact.py
  frappe/contacts/doctype/contact_email/contact_email.json
  frappe/contacts/doctype/contact_phone/contact_phone.json
  frappe/core/workspace/build/build.json
  frappe/core/workspace/users/users.json
  frappe/geo/languages.json
  frappe/integrations/workspace/integrations/integrations.json
  frappe/model/document.py
  frappe/public/js/frappe/form/templates/address_list.html
  frappe/public/js/frappe/form/templates/contact_list.html
  frappe/website/workspace/website/website.json
Labels: Review effort 3/5

#4 Update field labels in contact.json for consistency and clarity
  frappe/contacts/doctype/contact/contact.json
Labels: Review effort 1/5

#7 Enhance Address For Integration
  frappe/contacts/doctype/address/address.json
Labels: Review effort 1/5

#6 Refine Contact Doctype: Enhance Data Fields
  frappe/contacts/doctype/contact/contact.json
  frappe/contacts/doctype/contact/contact.py
  frappe/public/js/frappe/form/templates/contact_list.html
Labels: Review effort 2/5

#8 Chore/phone lang
  frappe/translations/vi.csv
Labels: Review effort 4/5

#10 feat: latest message
  frappe/contacts/doctype/contact/contact.json
  frappe/contacts/doctype/contact/contact.py
  frappe/www/contact.py
Labels: Review effort 2/5
